[tool.poetry]
name = "doop"
version = "0.0.1"
description = "orbital dynamics"
authors = ["walchko <walchko@users.noreply.github.com>"]
readme = "readme.md"
license = "MIT"
homepage = "https://pypi.org/project/doop/"
repository = 'https://github.com/nimbus-bp-1729/doop'
# documentation = "http://..."
keywords = ["orbit"]
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Topic :: Software Development :: Libraries',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Topic :: Software Development :: Libraries :: Application Frameworks'
]

# [tool.poetry.scripts]
# # script_name = 'myscript:main'

[tool.poetry.dependencies]
python = ">=3.6"
# numpy = "*"
# pyserial = "^3.4"
# colorama = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
# mypy = "*"

# [mypy-pi_servo_serial]
# ignore_missing_imports = True

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
