[tool.poetry]
name = "agilicus"
version = "1.4.1"
description = "Agilicus SDK"
license = "MIT"
authors = ["Don Bowman <don@agilicus.com>"]
readme = "README.md"
include = [ "agilicus_README.md" ]

[tool.poetry.dependencies]
python = "^3.7"
certifi = ">=14.05.14"
six = ">1.10"
python_dateutil = ">2.5.3"
urllib3 = ">1.15.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
