[tool.poetry]
name = "ofx-processor"
version = "0.5.0"
description = "Personal ofx processor"
readme = "README.md"
license = "GPL-3.0-or-later"
authors = ["Gabriel Augendre <gabriel@augendre.info>"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
]

[tool.poetry.dependencies]
python = ">=3.7"
ofxtools = "^0.8.20"
click = "^7.0"
dateparser = "^0.7.2"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"

[tool.poetry.scripts]
ynab = 'ofx_processor.main:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
