[tool.poetry]
name = "cli_contacts"
version = "0.5.0"
description = "A small CLI for managing contact information"
authors = ["Daníel Örn Árnason"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.8"
peewee = "^3.13.1"
click = "^7.0"
pydrive = "^1.3.1"
pandas = "^1.0.1"

[tool.poetry.dev-dependencies]
rope = "^0.16.0"
pylint = "^2.4.4"

[tool.poetry.scripts]
black-book = 'cli_contacts.cli_contacts:cli_contacts'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

