[tool.poetry]
name = "test_exe_matrix"
version = "0.1.3"
license = "GPL-2 or CECILL-2.1"
authors = [
    "Feth AREZKI <text_exe_matrix@tuttu.info>"
]
readme = 'README.rst'

repository = "https://framagit.org/feth/test_exe_matrix.git"
homepage = "https://framagit.org/feth/test_exe_matrix"

include = ["**/matrix.yaml"]

description = "Toy project to test executables defined in a yaml file"

[tool.poetry.dependencies]
python = ">= 3.6"
pytest = "5.3.1"
PyYAML = ">= 5.2"

[tool.poetry.scripts]
test_exe_matrix = 'test_exe_matrix.main:entrypoint'

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
black = "^19.10b0"
