[tool.poetry]
name = "csvy"
version = "0.1.3-alpha"
description = ""
authors = ["Mark Gemmill <gitlab@markgemmill.com>"]
readme = "README.md"
repository = "https://gitlab.com/mgemmill-pypi/csvy"
keywords = ["csv"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.dover]
versioned_files = ["pyproject.toml", "src/csvy/__init__.py"]
