[tool.poetry]
name = "gym_voltorb_flip"
version = "0.2.0-dev"
description = "A VoltorbFlip environment"
authors = ["Antonio Feregrino <antonio.feregrino@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
gym = "^0.16.0"
voltorb-flip = {version = "^0.2.0.dev0", allows-prereleases = true}

[tool.poetry.dev-dependencies]
advbumpversion = "^1.2"
bandit = "^1.6"
black = {version = "^18.3-alpha.0", allow-prereleases = true}
isort = "^4.3"
pylint = "^2.4"
pytest = "^5.2"
pytest-cov = "^2.8"
jupyter = "^1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
